version: '3.8'

services:
  frontend:
    build:
      context: ./inforce-front
    ports:
      - "3000:80"
    volumes:
      - ./inforce-front:/app
    depends_on:
      - database

  backend:
    build:
      context: ./app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/inforce_test_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inforce_test_db
    ports:
      - "5432:5432"

